In [1]:
import numpy as np

In [4]:
import numpy as np

# From a list
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# From a list of lists (2D array)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

# Using NumPy functions
zeros = np.zeros((3, 3))  # 3x3 array of zeros
print(zeros)

ones = np.ones((2, 4))  # 2x4 array of ones
print(ones)

arange = np.arange(0, 10, 2)  # Array with a range of values np.arange(start,stop,step) and [stop] is not included
print(arange)

print()
linspace = np.linspace(0, 1, 5)  # Array with 5 values linearly spaced between 0 and 1 np.arange(start,stop,no. of intervels)
for i in linspace:
    print(i,end="  ")


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]

0.0  0.25  0.5  0.75  1.0  

In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
sum_arr = arr1 + arr2
print(sum_arr)

# Element-wise subtraction
diff_arr = arr1 - arr2
print(diff_arr)

# Element-wise multiplication
prod_arr = arr1 * arr2
print(prod_arr)

# Element-wise division
div_arr = arr1 / arr2
print(div_arr)

# Scalar operations
scalar_mult = arr1 * 2
print(scalar_mult)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[2 4 6]


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Slicing
print(arr[1:4])  # Elements from index 1 to 3
print(arr[:3])   # First three elements
print(arr[3:])   # Elements from index 3 to the end

# Indexing
print(arr[2])    # Element at index 2

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])  # Element at row 1, column 2
print(arr_2d[:, 1])  # All elements in column 1
print(arr_2d[1, :])  # All elements in row 1

[2 3 4]
[1 2 3]
[4 5 6]
3
6
[2 5 8]
[4 5 6]


In [7]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Shape of the array
print(arr.shape)

# Reshape the array
reshaped_arr = arr.reshape((3, 2))
print(reshaped_arr)

# Flatten the array
flattened_arr = arr.flatten()
print(flattened_arr)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Mean
mean_val = np.mean(arr)
print(mean_val)

# Median
median_val = np.median(arr)
print(median_val)

# Standard deviation
std_val = np.std(arr)
print(std_val)

# Sum
sum_val = np.sum(arr)
print(sum_val)

# Maximum and minimum
max_val = np.max(arr)
print(max_val)
min_val = np.min(arr)
print(min_val)

3.0
3.0
1.4142135623730951
15
5
1


In [9]:
import numpy as np

# Random array of given shape
rand_arr = np.random.rand(3, 2)
print(rand_arr)

# Random integers in a given range
rand_int_arr = np.random.randint(0, 10, (3, 3))
print(rand_int_arr)

# Normal distribution
rand_normal = np.random.normal(0, 1, 5)  # Mean = 0, Std = 1, 5 elements
print(rand_normal)

[[0.91733248 0.0210276 ]
 [0.8832601  0.07524378]
 [0.92854014 0.71950225]]
[[2 6 5]
 [1 0 9]
 [4 0 7]]
[-1.90862719 -0.14422308  0.6422749  -0.4440857  -1.64930268]


In [10]:
import numpy as np

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
mat_mult = np.dot(mat1, mat2)
print(mat_mult)

# Transpose of a matrix
mat_transpose = mat1.T
print(mat_transpose)

# Inverse of a matrix
mat_inverse = np.linalg.inv(mat1)
print(mat_inverse)

# Determinant of a matrix
mat_det = np.linalg.det(mat1)
print(mat_det)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
